drop table if exists tcq_notification_defs;
create table tcq_notification_defs (
    id              number generated by default on null as identity
                    constraint tcq_notification_defs_id_pk primary key,
    owner           varchar2(50 char) not null
                    constraint tcq_notification_defs_owner_uk unique,
    reg_id          number not null,
    query_id_sal    number,
    query_Id_comm   number
);

drop table if exists tcq_notifications;
create table tcq_notifications (
    id          number generated by default on null as identity
                 constraint tcq_notifications_id_pk primary key,
    receiver    varchar2(50 char) not null,
    message     varchar2(4000 char),
    sent_date   date default on null sysdate not null
);

/*
 * Tables used in the examples in the official documentation.
 * 
 * Database Development Guide, Release 26
 * 21 Using Continuous Query Notification (CQN)
 * https://docs.oracle.com/en/database/oracle/oracle-database/26/adfns/cqn.html#GUID-2D194274-3C78-42F3-959C-10B9F30B2F07
 * Example 21-6 Creating Server-Side PL/SQL Notification Handler
 */

-- Create table to record notification events.
DROP TABLE if exists nfevents;
CREATE TABLE nfevents (
  regid      NUMBER,
  event_type NUMBER
);

-- Create table to record notification queries:
DROP TABLE if exists nfqueries;
CREATE TABLE nfqueries (
  qid NUMBER,
  qop NUMBER
);

-- Create table to record changes to registered tables:
DROP TABLE if exists nftablechanges;
CREATE TABLE nftablechanges (
  qid             NUMBER,
  table_name      VARCHAR2(100),
  table_operation NUMBER
);

-- Create table to record ROWIDs of changed rows:
DROP TABLE if exists nfrowchanges;
CREATE TABLE nfrowchanges (
  qid        NUMBER,
  table_name VARCHAR2(100),
  row_id     VARCHAR2(2000)
);