create table ebaj_csp_reports (
    id         number generated by default on null as identity
               constraint ebaj_csp_reports_id_pk primary key,
    report     clob check (report is json),
    created    date default on null sysdate
);