create table cwr_xliff_files (
    id                       number generated by default on null as identity
                             constraint cwr_xliff_files_id_pk primary key,
    name                     varchar2(255 char) not null,
    source_lang              varchar2(50 char),
    target_lang              varchar2(50 char),
    xliff_result             blob,
    xliff_result_filename    varchar2(255 char),
    xliff_result_mimetype    varchar2(255 char),
    xliff_result_charset     varchar2(255 char),
    xliff_result_lastupd     date,
    xliff_source             blob,
    xliff_source_filename    varchar2(255 char),
    xliff_source_mimetype    varchar2(255 char),
    xliff_source_charset     varchar2(255 char),
    xliff_source_lastupd     date
);



create table cwr_messages (
    id                  number generated by default on null as identity
                        constraint cwr_messages_id_pk primary key,
    name                varchar2(255 char),
    message_language    varchar2(50 char),
    message_text        varchar2(4000 char)
);